[package]
name = "soiyomi"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5", features = ["derive"] }
clipboard-stream = "0.2"
futures = { version = "0.3", features = ["executor", "thread-pool"] }
rodio = "0.21"
thiserror = "2.0.16"
